services:
  db:
    build: .
    container_name: postgres_but3
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpassword
      # Forces the database cluster to initialize with French collation
      POSTGRES_INITDB_ARGS: "--locale=fr_FR.utf8" 
      POSTGRES_DB: multi_lang
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: